# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Call for Papers
    url: /#call-for-papers
    weight: 20
  - name: Speakers
    url: /#speakers
    weight: 25
  - name: Schedule
    url: /#schedule
    weight: 30
  - name: Call for Reviewers
    url: /#call-for-reviewers
    weight: 40
  - name: Organization
    url: /#organization
    weight: 50

